# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dev\DevTool\Dev\Tool Distributor\UIC\mainwindow.ui'
#
# Created: Fri Jul 04 11:27:23 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 479)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.hostName_editBox = QtGui.QLineEdit(self.centralWidget)
        self.hostName_editBox.setMinimumSize(QtCore.QSize(171, 20))
        self.hostName_editBox.setObjectName("hostName_editBox")
        self.gridLayout.addWidget(self.hostName_editBox, 1, 0, 1, 1)
        self.pathDialog_button = QtGui.QToolButton(self.centralWidget)
        self.pathDialog_button.setMinimumSize(QtCore.QSize(41, 21))
        self.pathDialog_button.setMaximumSize(QtCore.QSize(41, 22))
        self.pathDialog_button.setObjectName("pathDialog_button")
        self.gridLayout.addWidget(self.pathDialog_button, 3, 1, 1, 1)
        self.setupPy_EditBox = QtGui.QLineEdit(self.centralWidget)
        self.setupPy_EditBox.setMinimumSize(QtCore.QSize(171, 20))
        self.setupPy_EditBox.setObjectName("setupPy_EditBox")
        self.gridLayout.addWidget(self.setupPy_EditBox, 3, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.port_editbox = QtGui.QLineEdit(self.centralWidget)
        self.port_editbox.setMinimumSize(QtCore.QSize(41, 20))
        self.port_editbox.setMaximumSize(QtCore.QSize(41, 20))
        self.port_editbox.setObjectName("port_editbox")
        self.gridLayout.addWidget(self.port_editbox, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setMaximumSize(QtCore.QSize(150, 100))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.versionRefresh_button = QtGui.QPushButton(self.groupBox)
        self.versionRefresh_button.setObjectName("versionRefresh_button")
        self.gridLayout_2.addWidget(self.versionRefresh_button, 3, 0, 1, 3)
        self.trivialVersion_editBox = QtGui.QLineEdit(self.groupBox)
        self.trivialVersion_editBox.setMaximumSize(QtCore.QSize(40, 20))
        self.trivialVersion_editBox.setObjectName("trivialVersion_editBox")
        self.gridLayout_2.addWidget(self.trivialVersion_editBox, 2, 2, 1, 1)
        self.minorVersion_editBox = QtGui.QLineEdit(self.groupBox)
        self.minorVersion_editBox.setMaximumSize(QtCore.QSize(40, 20))
        self.minorVersion_editBox.setObjectName("minorVersion_editBox")
        self.gridLayout_2.addWidget(self.minorVersion_editBox, 2, 1, 1, 1)
        self.majorVersion_editBox = QtGui.QLineEdit(self.groupBox)
        self.majorVersion_editBox.setMaximumSize(QtCore.QSize(40, 20))
        self.majorVersion_editBox.setObjectName("majorVersion_editBox")
        self.gridLayout_2.addWidget(self.majorVersion_editBox, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 3)
        self.gridLayout.addWidget(self.groupBox, 0, 2, 4, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.upload_button = QtGui.QPushButton(self.centralWidget)
        self.upload_button.setMinimumSize(QtCore.QSize(140, 61))
        self.upload_button.setObjectName("upload_button")
        self.horizontalLayout.addWidget(self.upload_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.output_editBox = QtGui.QTextEdit(self.centralWidget)
        self.output_editBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.output_editBox.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.output_editBox.setReadOnly(True)
        self.output_editBox.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.output_editBox.setObjectName("output_editBox")
        self.verticalLayout.addWidget(self.output_editBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 541, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.hostName_editBox, self.port_editbox)
        MainWindow.setTabOrder(self.port_editbox, self.setupPy_EditBox)
        MainWindow.setTabOrder(self.setupPy_EditBox, self.pathDialog_button)
        MainWindow.setTabOrder(self.pathDialog_button, self.majorVersion_editBox)
        MainWindow.setTabOrder(self.majorVersion_editBox, self.minorVersion_editBox)
        MainWindow.setTabOrder(self.minorVersion_editBox, self.trivialVersion_editBox)
        MainWindow.setTabOrder(self.trivialVersion_editBox, self.versionRefresh_button)
        MainWindow.setTabOrder(self.versionRefresh_button, self.upload_button)
        MainWindow.setTabOrder(self.upload_button, self.output_editBox)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.hostName_editBox.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "host name", None, QtGui.QApplication.UnicodeUTF8))
        self.pathDialog_button.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.setupPy_EditBox.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "setup.py filepath", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "setup.py filepath", None, QtGui.QApplication.UnicodeUTF8))
        self.port_editbox.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "port", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "host name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "port", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "property", None, QtGui.QApplication.UnicodeUTF8))
        self.versionRefresh_button.setText(QtGui.QApplication.translate("MainWindow", "version refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Major/Minor/Trivial", None, QtGui.QApplication.UnicodeUTF8))
        self.upload_button.setText(QtGui.QApplication.translate("MainWindow", "upload", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "output", None, QtGui.QApplication.UnicodeUTF8))

